name: Python Linting

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'main'

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff

    - name: Run unit tests
      run: python -m unittest discover -s tests -p 'test_*.py'

    - name: Run Ruff
      run: ruff check --output-format=github src

    - name: Run Ruff and check for errors
      run: |
        ruff_output=$(ruff check src)
        echo "$ruff_output"
        # error_count=$(echo "$ruff_output" | grep -c "error")
        # if (( error_count > 0 )); then
        #   exit 1
        # fi
