name: Python Package CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'docs/**'

permissions:
  contents: write
  id-token: write

# todo: 
# - remove test/lint (already in feature pipelines)
# - 3jobs: bump/package/publish
# - 
# - 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        persist-credentials: true
        ref: main

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # lint and unit tests
    - name: Run unit tests
      run: python -m unittest discover -s tests -p 'test_*.py'

    - name: Run Ruff
      run: ruff check --output-format=github src


    # version increment
    - name: Set up Git user for bump2version commit
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"    

    - name: Bump version and push tag
      run: |
        pip install --upgrade bump2version
        bump2version patch --allow-dirty
        
    - name: Push version bump to main
      run: |
        git push origin HEAD:main --tags

    # build package
    - name: Build Python package
      run: python setup.py sdist bdist_wheel

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
      
